base_local_planner:
  type: "base_local_planner/TrajectoryPlannerROS"
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 0.3
  min_in_place_rotational_vel: 0.1
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  holonomic_robot: false
