controller_frequency: 10.0

# Costmaps configuration
global_costmap_params:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  static_map: true

local_costmap_params:
  global_frame: "odom"
  robot_base_frame: "base_link"
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false

recovery_behaviors:
  - name: "rotate_recovery"
    type: "rotate_recovery/RotateRecovery"
    frequency: 1.0
    clearance_recovery_behavior: true
    preemption_recovery_behavior: false
